### ISSUE TITLE
Couldn't install the package

### ISSUE THREAD

**Issue by brunomontezano** [chrisaberson/BetterReg#2]
Hey @chrisaberson,

I've tried installing your package on 2022/04/05 (today) and couldn't get it working. I've tried installing with `remotes::install_github("chrisaberson/BetterReg")` but I've got an error about `undefined exports: depbcomp`.

Do you know what it could be?

**Comment by chrisaberson** [comment]
What platform are you using? I can check on this shortly. In the meantime,
the version on CRAN is passing all checks

**Comment by chrisaberson** [comment]
Should be fixed on git now - my apologies. I had the Rd rather than R file in the R directory.

**Comment by brunomontezano** [comment]
I'm on Linux @chrisaberson. Thanks for your promptness on fixing it!

**Comment by jbytecode** [comment]
Due to https://github.com/openjournals/joss-reviews/issues/4280
