### ISSUE TITLE
Paper improvements

### ISSUE THREAD

**Issue by brunomontezano** [chrisaberson/BetterReg#5]
Dear @chrisaberson,

I'd suggest you to add some more information about these points:

- [x] Installation instructions (List the three dependencies in your README - [car](https://cran.r-project.org/web/packages/car/index.html) (≥ 3.0-0), stats (≥ 3.5.0), [dplyr](https://cran.r-project.org/web/packages/dplyr/index.html) (≥ 0.8.0))
- [x] Community guidelines (specify how other contributors could contribute to the source code or add other new functionalities, how they can report issues or problems with the package and how they can ask for help about your package)
- [x] Target audience (in your paper, you could add in your Statement of Need, who's your target audience in this package)
- [x] State of the field (maybe you could add some information about the availability of this kind of analysis in other programming languages/packages or software, or or highlight the challenge of manually performing the tasks automated by your package previously in R)

Edit:
- [x] I'd suggest you to add some example code in your repo README as well

**Comment by brunomontezano** [comment]
Due to https://github.com/openjournals/joss-reviews/issues/4280

**Comment by chrisaberson** [comment]
Thank you for the comments - I have added the requested installation information, community guidelines, target audience, and state of the field. The repo now has more detailed example code.

**Comment by brunomontezano** [comment]
Great for now then, I'm going to close the issue. Great work!
